nelmio_api_doc:
    documentation:
        info:
            title: Verse Technical Test API Specification
            description: This aims to be a sandbox for the api but it'll just be for doc purposes
            version: 0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
